#+title: Kasten --- Zettelkasten note browser
#+author: Qiyang Sun

* Overview

=Kasten= is an [[https://www.gnu.org/software/emacs/][Emacs]] package designed to provide a focused and efficient
browsing experience for Zettelkasten-style notes. With Kasten, one can quickly
find, tag, and navigate notes stored locally.

* License

Kasten is licensed under the [[https://www.gnu.org/licenses/gpl-3.0.en.html][GNU General Public License Version 3]].

See the file =COPYING= for details.

*Copyright (C) 2025 Qiyang Sun*

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.

* Documentation

*Kasten Manual can be found [[https://iamsqy.github.io/kasten/][here]]*, in various of formats, containing following
important information and other useful information:
- *(@@html:<ins>@@Please visit [[https://iamsqy.github.io/kasten/]] for full
  manual!@@html:</ins>@@)*
- [[https://iamsqy.github.io/kasten/kasten_html/Copying.html][Copying]] (License)
- Concepts and Features
- [[https://iamsqy.github.io/kasten/kasten_html/Installation.html][Installation]], [[https://iamsqy.github.io/kasten/kasten_html/Usage.html][Usage]] and [[https://iamsqy.github.io/kasten/kasten_html/Customisation.html][Customisation]]
- [[https://iamsqy.github.io/kasten/kasten_html/Contributing.html][Contributing]]
- [[https://iamsqy.github.io/kasten/kasten_html/Too-Long_003b-Didn_0027t-Read.html][TL;DR]]

The /Kasten Manual/ is licensed under GNU Free Documentation License
Version 1.3.


#+html: <p><a href="https://orgmode.org"><img src="https://img.shields.io/badge/Org-Document-%2377aa99?style=flat-square&logo=org&logoColor=white"></a> <a href="https://www.gnu.org/software/emacs/"><img src="https://img.shields.io/badge/Made_with-Emacs-blueviolet.svg?style=flat-square&logo=GNU%20Emacs&logoColor=white"></a></p>
